import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import LearningModule from '../models/LearningModule';

dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const createModule = (cat: any, title: string, content: string, questions: any[], tier: number = 1) => ({
    category: cat,
    title,
    content,
    tier,
    points: 50,
    quiz: questions
});

const modules = [
    // SIP (5)
    createModule('sip', 'SIP Basics: The Discipline of Wealth', 
        'A Systematic Investment Plan (SIP) is a method where you invest a fixed amount in a mutual fund scheme periodically at regular intervals. It is not just an investment; it is a saving habit. By investing a small amount every month, you can build a significant corpus over time.\n\nThe biggest advantage is Rupee Cost Averaging. When the market is high, you buy fewer units; when it is low, you buy more. This averages out the cost of acquisition and reduces risk. Starting early is the key to maximizing the power of compounding.',
        [
            { question: 'What is the primary benefit of SIP?', options: ['Rupee Cost Averaging', 'Guaranteed high returns', 'No risk at all'], correctIndex: 0 },
            { question: 'Do you need to time the market for SIP?', options: ['Yes, always buy low', 'No, consistency is more important', 'Only during holidays'], correctIndex: 1 },
            { question: 'How often can you invest in a SIP?', options: ['Only yearly', 'Daily, Monthly, or Quarterly', 'Only when you have extra cash'], correctIndex: 1 },
            { question: 'Can SIP help in building a long-term corpus?', options: ['Yes', 'No', 'Only for 1 month'], correctIndex: 0 },
            { question: 'What is the "engine" of SIP wealth?', options: ['Inflation', 'Compounding', 'Taxes'], correctIndex: 1 }
        ]
    ),
    createModule('sip', 'The Power of Compounding', 
        'Compounding is often called the eighth wonder of the world. It is the process where the returns generated by your investment start earning their own returns. The longer the timeframe, the more explosive the growth.\n\nFor example, starting a ₹5000 SIP at age 20 vs. age 30 can lead to a difference of crores in the final balance at age 60. Time is your best friend in the stock market.',
        [
            { question: 'What is compounding?', options: ['Interest on Principal only', 'Interest on Interest', 'Fixed monthly payout'], correctIndex: 1 },
            { question: 'When is compounding most effective?', options: ['Short term', 'Long term', 'Medium term'], correctIndex: 1 },
            { question: 'Starting early results in:', options: ['Less money', 'Exponentially more money', 'Same money'], correctIndex: 1 },
            { question: 'Does compounding work on small amounts?', options: ['Yes', 'No', 'Only on lakhs'], correctIndex: 0 },
            { question: 'Which factor matters most for compounding?', options: ['Luck', 'Investment Tier', 'Time'], correctIndex: 2 }
        ], 2
    ),
    createModule('sip', 'Rupee Cost Averaging', 
        'Rupee Cost Averaging is a strategy where you invest a fixed amount of money at regular intervals, regardless of the share price. Because you invest the same amount every month, you automatically buy more units when prices are low and fewer units when prices are high.\n\nThis takes the emotion out of investing and ensures you don\'t buy everything at a market peak.',
        [
            { question: 'When do you buy more units in SIP?', options: ['When price is high', 'When price is low', 'Always same units'], correctIndex: 1 },
            { question: 'What emotion does SIP help control?', options: ['Greed and Fear', 'Happiness', 'Sadness'], correctIndex: 0 },
            { question: 'Is market volatility good for SIP?', options: ['No, it hurts', 'Yes, it allows buying at dips', 'Doesn\'t matter'], correctIndex: 1 },
            { question: 'Does Rupee Cost Averaging guarantee profit?', options: ['Yes', 'No, but it reduces average cost', 'Maybe'], correctIndex: 1 },
            { question: 'Should you stop SIP during market crashes?', options: ['Yes, save money', 'No, crashes are buying opportunities', 'Only if you need cash'], correctIndex: 1 }
        ], 2
    ),
    createModule('sip', 'Step-up SIP: Increasing Contributions', 
        'A Step-up SIP allows you to increase your SIP amount periodically. Most people get an annual salary hike; a Step-up SIP follows this pattern. Increasing your ₹10,000 SIP by just 10% every year can double your target corpus in half the time.\n\nIt is one of the most powerful tools for rapid wealth building.',
        [
            { question: 'What is a Step-up SIP?', options: ['Pausing SIP', 'Increasing SIP amount regularly', 'Withdrawing SIP'], correctIndex: 1 },
            { question: 'When is the best time to step-up?', options: ['Market crash', 'After a salary hike', 'Birthdays'], correctIndex: 1 },
            { question: 'Benefit of Step-up SIP:', options: ['Reach goals faster', 'Reduce risk', 'Avoid taxes'], correctIndex: 0 },
            { question: 'Can you step-up by a percentage?', options: ['Yes', 'No', 'Only by fixed amount'], correctIndex: 0 },
            { question: 'Is Step-up SIP automated usually?', options: ['Yes', 'No', 'Requires manual work every month'], correctIndex: 0 }
        ], 3
    ),
    createModule('sip', 'Multi-Asset SIPs', 
        'Asset allocation is the key to peace of mind. A Multi-Asset SIP distributes your money across Stocks, Gold, and Bonds. When stocks go down, gold often goes up. This diversification protects your portfolio from extreme volatility while providing steady growth.',
        [
            { question: 'What is diversification?', options: ['Investing in one stock', 'Spreading money across assets', 'Giving money to family'], correctIndex: 1 },
            { question: 'Why include Gold in SIP?', options: ['It is shiny', 'Safe haven during crashes', 'High yield dividends'], correctIndex: 1 },
            { question: 'Multi-asset SIP improves:', options: ['Risk-adjusted returns', 'Total loss', 'Pure greed'], correctIndex: 0 },
            { question: 'Which asset is usually safest?', options: ['Stocks', 'Bonds', 'Crypto'], correctIndex: 1 },
            { question: 'Does multi-asset SIP require rebalancing?', options: ['Yes', 'No', 'Never'], correctIndex: 0 }
        ], 3
    ),

    // FD (4)
    createModule('fd', 'Fixed Deposits: Safety First', 
        'Fixed Deposits (FD) are the bedrock of Indian savings. You deposit a sum for a fixed tenure at a fixed interest rate. It provides total capital safety and predictable returns.\n\nFDs are perfect for emergency funds and short-term goals. They are insured by DICGC up to ₹5 Lakhs per bank.',
        [
            { question: 'Is FD capital safe?', options: ['Yes, mostly', 'No, high risk', 'Only for 1 year'], correctIndex: 0 },
            { question: 'What is the insurance limit on FDs in India?', options: ['1 Lakh', '5 Lakhs', '10 Lakhs'], correctIndex: 1 },
            { question: 'Who provides FD insurance?', options: ['RBI', 'DICGC', 'SEBI'], correctIndex: 1 },
            { question: 'Return on FD is:', options: ['Fixed', 'Variable', 'Random'], correctIndex: 0 },
            { question: 'Best use of FD?', options: ['Gambling', 'Emergency Fund', 'Daily trading'], correctIndex: 1 }
        ]
    ),
    createModule('fd', 'FD Laddering Technique', 
        'FD Laddering is a strategy to beat liquidity issues. Instead of putting ₹5 Lakhs in one FD for 5 years, you put ₹1 Lakh each in FDs for 1, 2, 3, 4, and 5 years. Every year, one FD matures, providing cash flow or allowing you to reinvest at current higher rates.',
        [
            { question: 'What is FD Laddering?', options: ['Stacking coins', 'Splitting FDs into various tenures', 'Climbing a ladder for luck'], correctIndex: 1 },
            { question: 'Main benefit of Laddering:', options: ['Higher risk', 'Better liquidity and rate averaging', 'No interest'], correctIndex: 1 },
            { question: 'How often do FDs mature in a perfect 5-year ladder?', options: ['Monthly', 'Every year', 'Every 5 years'], correctIndex: 1 },
            { question: 'Does laddering help if rates go up?', options: ['Yes, can reinvest at new rates', 'No', 'Only if bank is small'], correctIndex: 0 },
            { question: 'Is it more complex than a single FD?', options: ['Slightly, but worthwhile', 'Much easier', 'Exactly same'], correctIndex: 0 }
        ], 2
    ),
    createModule('fd', 'Taxation on FD Interest', 
        'Interest earned on FDs is taxable as per your income tax slab. If interest exceeds ₹40,000 in a year (₹50,000 for seniors), banks deduct 10% TDS. You can submit Form 15G/15H if your total income is below the taxable limit to avoid this deduction.',
        [
            { question: 'Is FD interest tax-free?', options: ['Yes', 'No, taxable as per slab', 'Only for students'], correctIndex: 1 },
            { question: 'What is TDS limit for regular citizens?', options: ['₹10,000', '₹40,000', '₹1 Lakh'], correctIndex: 1 },
            { question: 'Which form avoids TDS if income is low?', options: ['Form 10A', 'Form 15G/15H', 'Form 16'], correctIndex: 1 },
            { question: 'TDS rate on FD is usually:', options: ['5%', '10%', '30%'], correctIndex: 1 },
            { question: 'Can you get a refund of TDS?', options: ['Yes, while filing ITR', 'No, bank keeps it', 'Only after 10 years'], correctIndex: 0 }
        ], 2
    ),
    createModule('fd', 'FD vs Debt Mutual Funds', 
        'While FDs offer fixed returns, Debt Mutual Funds offer market-linked returns and potentially better tax efficiency. Debt funds are more liquid (usually T+1) but carry slight interest rate risk. FDs are better for peace of mind, while Debt funds are for slightly higher efficiency.',
        [
            { question: 'Debt MFs are better for:', options: ['Capital safety', 'Tax efficiency', 'Guaranteed returns'], correctIndex: 1 },
            { question: 'Do Debt Funds have guaranteed returns?', options: ['Yes', 'No, they are market linked', 'Only on Fridays'], correctIndex: 1 },
            { question: 'Which is more liquid?', options: ['FD (No penalty)', 'Debt Funds (Usually 1 day)', 'Both same'], correctIndex: 1 },
            { question: 'Does FD have a penalty for early withdrawal?', options: ['Usually yes', 'Never', 'Only if bank is local'], correctIndex: 0 },
            { question: 'Inflation beats which one easier?', options: ['FD', 'Debt Funds', 'Neither'], correctIndex: 0 }
        ], 3
    ),

    // Market (4)
    createModule('market', 'Stock Market Basics', 
        'The stock market is a platform where shares of public companies are bought and sold. A share represents part ownership in a company. When you buy a share, you become a "shareholder". Stocks have historically outperformed all other asset classes over long horizons.',
        [
            { question: 'What is a stock?', options: ['A loan to company', 'Ownership in company', 'A type of bond'], correctIndex: 1 },
            { question: 'What is a dividend?', options: ['A tax you pay', 'Profit shared by company', 'A trading fee'], correctIndex: 1 },
            { question: 'What is NSE?', options: ['New Stock Entity', 'National Stock Exchange', 'Never Sell Everything'], correctIndex: 1 },
            { question: 'Primary goal of buying stocks?', options: ['Give away money', 'Capital appreciation', 'Help the government'], correctIndex: 1 },
            { question: 'Are stocks risky in short term?', options: ['Yes, highly', 'No, stable', 'Only on weekends'], correctIndex: 0 }
        ]
    ),
    createModule('market', 'Blue Chip vs Penny Stocks', 
        'Blue-chip companies are large, well-established, and financially sound institutions (like Reliance, HDFC, TCS). Penny stocks are low-priced, small companies with high risk and low liquidity. Blue chips are for stability; Penny stocks are often for gambling.',
        [
            { question: 'What is a Blue Chip?', options: ['A blue colored stock', 'A large, stable company', 'A software bug'], correctIndex: 1 },
            { question: 'Risk in Penny stocks is:', options: ['Zero', 'Extreme', 'Medium'], correctIndex: 1 },
            { question: 'Which is more liquid?', options: ['Blue chips', 'Penny stocks', 'Small caps'], correctIndex: 0 },
            { question: 'Penny stocks trade at:', options: ['Lakhs', 'Very low prices', 'Fixed rates'], correctIndex: 1 },
            { question: 'Blue chips usually provide:', options: ['Dividends and stability', '100% daily growth', 'Pure loss'], correctIndex: 0 }
        ], 2
    ),
    createModule('market', 'Index Funds & ETFs', 
        'Index funds track a specific market index like the Nifty 50. They are "passive" because no fund manager is picking stocks. They have very low fees. Warren Buffett recommends index funds to almost every beginner investor.',
        [
            { question: 'What is Nifty 50?', options: ['Top 50 companies in India', '50 types of stocks', 'A lucky number'], correctIndex: 0 },
            { question: 'Benefit of Index Funds:', options: ['High manager fee', 'Low cost and diversification', 'Market beating returns always'], correctIndex: 1 },
            { question: 'Expense ratio in Index funds is:', options: ['High', 'Low', 'Zero'], correctIndex: 1 },
            { question: 'Are index funds passive?', options: ['Yes', 'No', 'Only on Mondays'], correctIndex: 0 },
            { question: 'Does index fund track market?', options: ['Yes', 'No, it tracks gold', 'Sometimes'], correctIndex: 0 }
        ], 2
    ),
    createModule('market', 'PE Ratio & Ratios', 
        'The Price-to-Earnings (PE) ratio tells you how much investors are willing to pay for every ₹1 of company profit. A high PE might mean a stock is overvalued or has high growth potential. Comparing PE with industry average is a key fundamental analysis step.',
        [
            { question: 'What does PE ratio mean?', options: ['Price to Earnings', 'Post Entry', 'Property Equity'], correctIndex: 0 },
            { question: 'High PE always means bad buy?', options: ['Yes', 'No, could mean growth', 'Depends on weather'], correctIndex: 1 },
            { question: 'Earnings in PE refers to:', options: ['Topline', 'Net Profit', 'Taxes'], correctIndex: 1 },
            { question: 'Should you combine PE with other ratios?', options: ['Yes, like Debt-to-Equity', 'No, PE is enough', 'Only for traders'], correctIndex: 0 },
            { question: 'Debt-to-Equity should ideally be:', options: ['Very high', 'Lower is usually safer', 'Infinity'], correctIndex: 1 }
        ], 3
    ),

    // Real Estate (4)
    createModule('realestate', 'Real Estate: The Tangible Asset', 
        'Real estate involves buying land or buildings. It offers dual returns: Rental Income and Capital Appreciation. It is often seen as a status symbol and a hedge against inflation. However, it requires huge capital and has very low liquidity.',
        [
            { question: 'Types of Real Estate returns?', options: ['Rent and Appreciation', 'Only Selling', 'Only Dividend'], correctIndex: 0 },
            { question: 'Downside of Real Estate:', options: ['Low liquidity', 'High safety', 'Low cost'], correctIndex: 0 },
            { question: 'Does it hedge against inflation?', options: ['Yes', 'No', 'Only sometimes'], correctIndex: 0 },
            { question: 'Maintenance cost is a:', options: ['Profit', 'Liability', 'Asset'], correctIndex: 1 },
            { question: 'Is physical property easy to sell?', options: ['No, takes months', 'Yes, instantly', 'Only in 1 hour'], correctIndex: 0 }
        ]
    ),
    createModule('realestate', 'Residential vs Commercial', 
        'Residential property is for living, while commercial is for business. Commercial usually yields higher rental (6-8%) compared to residential (2-3%), but requires higher capital and has more complex legalities.',
        [
            { question: 'Commercial property yield is usually:', options: ['Lower than residential', 'Higher than residential', 'Same'], correctIndex: 1 },
            { question: 'Typical residential rent yield in India?', options: ['2-3%', '10-12%', '50%'], correctIndex: 0 },
            { question: 'Which has longer lease periods?', options: ['Residential', 'Commercial', 'Both same'], correctIndex: 1 },
            { question: 'Commercial property depends on:', options: ['Business cycles', 'Only weekends', 'Weather'], correctIndex: 0 },
            { question: 'Vacancies are more common in:', options: ['Residential', 'Commercial during recessions', 'Neither'], correctIndex: 1 }
        ], 2
    ),
    createModule('realestate', 'REITs: Property without hassle', 
        'Real Estate Investment Trusts (REITs) are like mutual funds for property. They own and manage income-generating commercial real estate. You can invest in them via the stock market with as little as ₹300, and you get 90% of profits as dividends.',
        [
            { question: 'What is a REIT?', options: ['A building tool', 'A property mutual fund', 'A tax form'], correctIndex: 1 },
            { question: 'REITs pass what % of profit to investors?', options: ['50%', '90%', '10%'], correctIndex: 1 },
            { question: 'Can you buy REITs on stock exchange?', options: ['Yes', 'No', 'Only from builders'], correctIndex: 0 },
            { question: 'Minimum investment in REITs is now:', options: ['₹50 Lakhs', '₹10,000 to ₹300', '₹1 Crore'], correctIndex: 1 },
            { question: 'REITs are more liquid than physical property?', options: ['Yes', 'No', 'Same'], correctIndex: 0 }
        ], 3
    ),
    createModule('realestate', 'Home Loans & EMIs', 
        'A home loan allows you to buy property now and pay over 20-30 years. The EMI consists of Principal and Interest. Tax benefits under Section 80C and 24(b) make home loans attractive for the middle class.',
        [
            { question: 'What is EMI?', options: ['Equal Market Index', 'Equated Monthly Installment', 'Easy Money India'], correctIndex: 1 },
            { question: 'Maximum tax deduction on interest?', options: ['₹50,000', '₹2 Lakhs', 'Unlimited'], correctIndex: 1 },
            { question: 'Tenure of home loan is usually:', options: ['1 year', '15-30 years', 'Daily'], correctIndex: 1 },
            { question: 'Down payment is usually:', options: ['0%', '10-20%', '100%'], correctIndex: 1 },
            { question: 'Interest rate types?', options: ['Fixed and Floating', 'Only Fixed', 'Random'], correctIndex: 0 }
        ], 2
    ),

    // Chit Funds (3)
    createModule('chitfund', 'Traditional Social Saving', 
        'Chit funds are social saving schemes where a group contributes monthly. The total "pot" is auctioned every month, and the highest bidder takes the money (usually someone in need). The discount offered by the bidder is shared among all members.',
        [
            { question: 'Chit funds are primarily for:', options: ['Gambling', 'Borrowing and Saving', 'Paying taxes'], correctIndex: 1 },
            { question: 'How is the pot winner chosen?', options: ['Lottery only', 'Reverse Auction', 'Manager choice'], correctIndex: 1 },
            { question: 'Benefit of Chit Fund:', options: ['No interest loans', 'Easy credit for small business', 'Guaranteed gold'], correctIndex: 1 },
            { question: 'Chit funds are popular in:', options: ['Cities only', 'Traditional communities', 'Only banks'], correctIndex: 1 },
            { question: 'Is it a pool of money?', options: ['Yes', 'No', 'Only digital points'], correctIndex: 0 }
        ]
    ),
    createModule('chitfund', 'Legal & Safety Aspect', 
        'Many chit funds are unregistered and risky. Only invest in "Registered Chit Funds" governed by the Chit Funds Act, 1982. These funds deposit security with the Registrar, making them much safer from fraud.',
        [
            { question: 'Regulation for Chit Funds?', options: ['SEBI', 'Chit Funds Act 1982', 'RBI only'], correctIndex: 1 },
            { question: 'Safest way to join?', options: ['Friend circle unreg', 'Registered firms', 'Online ads'], correctIndex: 1 },
            { question: 'Registrar of Chits provides:', options: ['Money', 'Safety and legal oversight', 'Taxes'], correctIndex: 1 },
            { question: 'Can unreg chits vanish?', options: ['Yes, high risk', 'Never', 'Only in winter'], correctIndex: 0 },
            { question: 'Check reputation of:', options: ['The Foreman', 'The Bank', 'The Neighbor'], correctIndex: 0 }
        ], 2
    ),
    createModule('chitfund', 'When to use Chit Funds?', 
        'Use chit funds if you are a small business owner needing lumpsum capital without bank documentation, or if you find bank FDs too boring and want a social element to saving. Avoid them for your core retirement corpus.',
        [
            { question: 'Best for whom?', options: ['Small business owners', 'Large tech firms', 'Retirees only'], correctIndex: 0 },
            { question: 'Documentation compared to banks:', options: ['Much more', 'Less / Flexible', 'Zero'], correctIndex: 1 },
            { question: 'Main risk factor:', options: ['Inflation', 'Counterparty default', 'Taxes'], correctIndex: 1 },
            { question: 'Yield calculation:', options: ['Fixed 10%', 'Depends on auction bids', 'Random'], correctIndex: 1 },
            { question: 'Should it be 100% of portfolio?', options: ['Yes', 'No, diversify', 'Maybe'], correctIndex: 1 }
        ], 2
    ),

    // Adding more to reach 37+ total
    // Crypto (4)
    createModule('crypto', 'Blockchain: The Ledger', 'Blockchain tech... transparency...', [
        { question: 'Is blockchain public?', options: ['Yes, usually', 'No, private only', 'Only for banks'], correctIndex: 0 },
        { question: 'Immutable means?', options: ['Can be changed', 'Cannot be changed', 'Only for admins'], correctIndex: 1 },
        { question: 'Centralized?', options: ['Yes', 'No', 'Maybe'], correctIndex: 1 },
        { question: 'Used in?', options: ['Only money', 'Supply chain, smart contracts, finance', 'Only gaming'], correctIndex: 1 },
        { question: 'Who controls a true blockchain?', options: ['Government', 'The network nodes', 'CEO'], correctIndex: 1 }
    ]),
    createModule('crypto', 'Bitcoin: Digital Gold', 'Bitcoin basics...', [
        { question: 'Max supply of Bitcoin?', options: ['Unlimited', '21 Million', '100 Million'], correctIndex: 1 },
        { question: 'Who created Bitcoin?', options: ['Elon Musk', 'Satoshi Nakamoto', 'Bill Gates'], correctIndex: 1 },
        { question: 'Store of Value?', options: ['Yes', 'No', 'Daily use only'], correctIndex: 0 },
        { question: 'Halving happens every:', options: ['Year', '4 years', '10 years'], correctIndex: 1 },
        { question: 'Is Bitcoin legal in India?', options: ['Banned', 'Not legal tender but taxable', 'Full legal tender'], correctIndex: 1 }
    ]),
    createModule('crypto', 'Ethereum & Smart Contracts', 'Ethereum tech...', [
        { question: 'Main feature of Ethereum?', options: ['Smart Contracts', 'Only fast speed', 'Free money'], correctIndex: 0 },
        { question: 'What is Gas fee?', options: ['Transaction fee', 'Petrol for mining', 'A tax'], correctIndex: 0 },
        { question: 'DeFi stands for:', options: ['Definite Finance', 'Decentralized Finance', 'Deep Finance'], correctIndex: 1 },
        { question: 'Is Ethereum PoS now?', options: ['Yes', 'No, PoW', 'Maybe'], correctIndex: 0 },
        { question: 'Can you build apps on it?', options: ['Yes', 'No', 'Only for banks'], correctIndex: 0 }
    ]),
    createModule('crypto', 'Security & Wallets', 'Cold vs Hot wallets...', [
        { question: 'Safest wallet type?', options: ['Hot Wallet', 'Cold Wallet / Hardware', 'Exchange'], correctIndex: 1 },
        { question: 'What is a Seed Phrase?', options: ['A random story', '12-24 words to recover funds', 'A password only'], correctIndex: 1 },
        { question: 'Should you share seed phrase?', options: ['Yes', 'No, NEVER', 'Only with support'], correctIndex: 1 },
        { question: 'Hot wallet is:', options: ['Connected to internet', 'Disconnected', 'Paid only'], correctIndex: 0 },
        { question: 'Phishing is a risk?', options: ['Yes', 'No', 'Only for old people'], correctIndex: 0 }
    ]),

    // Gold (3)
    createModule('gold', 'Gold: The Ancient Hedge', 'Gold preserves purchasing power...', [
        { question: 'Gold hedges against?', options: ['Profit', 'Inflation', 'Growth'], correctIndex: 1 },
        { question: 'Portfolio share?', options: ['100%', '5-10%', '0%'], correctIndex: 1 },
        { question: 'Physical gold risks?', options: ['Purity and theft', 'Daily growth', 'Banned'], correctIndex: 0 },
        { question: 'Does gold pay dividends?', options: ['Yes', 'No', 'Only gold coins'], correctIndex: 1 },
        { question: 'Price moves with?', options: ['Global economy', 'Daily weather', 'Only India'], correctIndex: 0 }
    ]),
    createModule('gold', 'Digital Gold & SGBs', 'SGBs (Sovereign Gold Bonds)...', [
        { question: 'Best gold investment today?', options: ['Jewelry', 'SGB (Sovereign Gold Bonds)', 'Gold bars'], correctIndex: 1 },
        { question: 'Interest in SGB?', options: ['Zero', '2.5% per year', '10%'], correctIndex: 1 },
        { question: 'Capital gains in SGB if held to maturity?', options: ['Taxable', 'Tax-free', '50% tax'], correctIndex: 1 },
        { question: 'Issuer of SGB?', options: ['Private banks', 'RBI on behalf of Govt', 'Jewelers'], correctIndex: 1 },
        { question: 'SGB tenure?', options: ['1 year', '8 years', '1 month'], correctIndex: 1 }
    ]),
    createModule('gold', 'Jewelry as Investment?', 'Jewelry downsides...', [
        { question: 'Making charges in jewelry?', options: ['Gain', 'Loss / Cost', 'Profit'], correctIndex: 1 },
        { question: 'Is jewelry 100% pure?', options: ['Yes', 'No, usually 22K or 18K', 'Always'], correctIndex: 1 },
        { question: 'Loss while selling jewelry?', options: ['High due to wastage', 'Zero', 'Profit'], correctIndex: 0 },
        { question: 'Best purity for investment?', options: ['22K', '24K', '10K'], correctIndex: 1 },
        { question: 'Jewelry provides?', options: ['Emotional value', 'High cash yield', 'No risk'], correctIndex: 0 }
    ]),

    // Trading (3)
    createModule('trading', 'Trading Basics', 'Intraday vs Delivery...', [
        { question: 'Intraday timeframe?', options: ['1 year', '1 day', '1 week'], correctIndex: 1 },
        { question: 'Leverage is?', options: ['Free money', 'Borrowing to trade more', 'Guaranteed profit'], correctIndex: 1 },
        { question: 'Delivery trading means?', options: ['Selling today', 'Holding stocks', 'Fast delivery'], correctIndex: 1 },
        { question: 'Trading requires?', options: ['High patience', 'Fast decisions', 'Luck only'], correctIndex: 1 },
        { question: 'Chart patterns belong to?', options: ['Fundamental Analysis', 'Technical Analysis', 'Astrology'], correctIndex: 1 }
    ]),
    createModule('trading', 'Risk Management', 'Stop loss, Position sizing...', [
        { question: 'What is Stop Loss?', options: ['Stop your profit', 'Limit your loss', 'Stop trading'], correctIndex: 1 },
        { question: 'Position sizing is?', options: ['Bigger is better', 'Managing how much to buy', 'Random'], correctIndex: 1 },
        { question: 'Risk per trade target?', options: ['100%', '1-2%', '50%'], correctIndex: 1 },
        { question: 'Overtrading leads to?', options: ['Higher profits', 'High brokerage and loss', 'Happiness'], correctIndex: 1 },
        { question: 'Emotional trading is?', options: ['Good', 'Dangerous', 'Necessary'], correctIndex: 1 }
    ]),
    createModule('trading', 'Options & Futures', 'Derivatives intro...', [
        { question: 'Options are?', options: ['Stocks', 'Derivatives', 'Loans'], correctIndex: 1 },
        { question: 'Calls are for?', options: ['Bullish view', 'Bearish view', 'Flat view'], correctIndex: 0 },
        { question: 'Puts are for?', options: ['Bullish view', 'Bearish view', 'Flat view'], correctIndex: 1 },
        { question: 'Options risk for buyers?', options: ['Unlimited', 'Limited to premium', 'Zero'], correctIndex: 1 },
        { question: 'Options have expiry?', options: ['Yes', 'No, life time', 'Only for 1 month'], correctIndex: 0 }
    ]),

    // Mutual Funds & ETFs (4)
    createModule('mutualfunds', 'MF Categories', 'Equity, Debt, Hybrid...', [
        { question: 'Equity MFs buy?', options: ['Gold', 'Stocks', 'Bonds'], correctIndex: 1 },
        { question: 'ELSS is for?', options: ['Life insurance', 'Tax saving 80C', 'Gambling'], correctIndex: 1 },
        { question: 'Lock-in for ELSS?', options: ['Zero', '3 years', '10 years'], correctIndex: 1 },
        { question: 'Expense ratio?', options: ['A fee to manage fund', 'A tax', 'A dividend'], correctIndex: 0 },
        { question: 'Direct vs Regular?', options: ['Direct has lower fee', 'Regular is cheaper', 'Same'], correctIndex: 0 }
    ]),
    createModule('mutualfunds', 'Debt MF Dynamics', 'Interest rates and bonds...', [
        { question: 'Debt funds buy?', options: ['Stocks', 'Bonds/T-bills', 'Crypto'], correctIndex: 1 },
        { question: 'Liquid funds are for?', options: ['Long term', 'Short term / Emergency', 'High risk'], correctIndex: 1 },
        { question: 'Interest rate up, Bond price?', options: ['Up', 'Down', 'Same'], correctIndex: 1 },
        { question: 'Credit risk is?', options: ['Profit', 'Lender default risk', 'Bank fee'], correctIndex: 1 },
        { question: 'Duration risk?', options: ['Time risk', 'Volatility due to rate change', 'Expiries'], correctIndex: 1 }
    ]),
    createModule('etfs', 'ETF Advantage', 'Exchange traded funds...', [
        { question: 'ETFs trade on?', options: ['Bank counters', 'Stock Exchange', 'Only online apps'], correctIndex: 1 },
        { question: 'Pricing of ETFs is?', options: ['Once a day', 'Real-time', 'Monthly'], correctIndex: 1 },
        { question: 'Gold ETF represents?', options: ['Real gold units', 'Digital tokens', 'Bank notes'], correctIndex: 0 },
        { question: 'Liquidity is important for ETFs?', options: ['Yes', 'No', 'Only for large caps'], correctIndex: 0 },
        { question: 'Tracking error is?', options: ['Gain', 'Difference from index', 'Software bug'], correctIndex: 1 }
    ]),
    createModule('etfs', 'Passive vs Active', 'Fees and Alpha...', [
        { question: 'Index funds are?', options: ['Active', 'Passive', 'Aggressive'], correctIndex: 1 },
        { question: 'Who picks stocks in active fund?', options: ['Computer', 'Fund Manager', 'Investor'], correctIndex: 1 },
        { question: 'Alpha means?', options: ['Market return', 'Excess return vs benchmark', 'Loss'], correctIndex: 1 },
        { question: 'Beta means?', options: ['Market volatility', 'Profit', 'Fixed return'], correctIndex: 0 },
        { question: 'Lower fee is in?', options: ['Active', 'Passive', 'Both same'], correctIndex: 1 }
    ]),

    // Securities (4)
    createModule('security', 'Bonds Basics', 'Safest assets...', [
        { question: 'What is a Bond?', options: ['Ownership', 'Loan to Entity', 'Gift'], correctIndex: 1 },
        { question: 'Issuer of G-Secs?', options: ['RBI', 'Government', 'Private companies'], correctIndex: 1 },
        { question: 'Face Value is?', options: ['Market price', 'Issue price / Maturity value', 'Daily rate'], correctIndex: 1 },
        { question: 'Yield to Maturity (YTM)?', options: ['Annual return if held till end', 'Profit today', 'Tax'], correctIndex: 0 },
        { question: 'Bonds are safer than stocks?', options: ['Yes, usually', 'No', 'Same'], correctIndex: 0 }
    ]),
    createModule('security', 'Corporate Bonds', 'High yield but...', [
        { question: 'Corporate bonds have higher rate than G-Sec?', options: ['Yes', 'No', 'Default'], correctIndex: 0 },
        { question: 'Credit rating is for?', options: ['Safety check', 'Amount check', 'Bank check'], correctIndex: 0 },
        { question: 'AAA rated means?', options: ['Highest safety', 'High risk', 'Moderate'], correctIndex: 0 },
        { question: 'Junk bonds have?', options: ['High yield high risk', 'Low yield', 'No return'], correctIndex: 0 },
        { question: 'Default risk exists?', options: ['Yes', 'No', 'Only for gold'], correctIndex: 0 }
    ]),
    createModule('security', 'T-Bills & Short term', '91, 182, 364 days...', [
        { question: 'T-Bills are issued by?', options: ['State Govt', 'Central Govt', 'Local bank'], correctIndex: 1 },
        { question: 'Duration of T-Bills?', options: ['Up to 1 year', '10 years', 'Daily'], correctIndex: 0 },
        { question: 'Are T-Bills safe?', options: ['Sovereign safety', 'Market risk', 'Zero return'], correctIndex: 0 },
        { question: 'Sold at?', options: ['Premium', 'Discount to face value', 'Current price'], correctIndex: 1 },
        { question: 'Liquidity is high?', options: ['Yes', 'No', 'Only for NRIs'], correctIndex: 0 }
    ]),
    createModule('security', 'Inflation Indexed Bonds', 'Protecting your wealth...', [
        { question: 'IIB protects from?', options: ['Taxes', 'Inflation', 'Credit risk'], correctIndex: 1 },
        { question: 'Principal adjusts with CPI?', options: ['Yes', 'No', 'Daily'], correctIndex: 0 },
        { question: 'Real rate of return is?', options: ['Return above inflation', 'Gross return', 'Net of tax'], correctIndex: 0 },
        { question: 'Good for long term savers?', options: ['Yes', 'No', 'Only during crashes'], correctIndex: 0 },
        { question: 'Issued by?', options: ['Govt', 'Banks', 'Builders'], correctIndex: 0 }
    ])
];

// Ensure we have 37 modules (Categories: SIP 5, FD 4, Market 4, RealEstate 4, ChitFund 3, Crypto 4, Gold 3, Trading 3, MF 4, Security 4 = 38 modules)

const seedDB = async () => {
    try {
        const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/finvista';
        console.log('Connecting to:', mongoUri);
        await mongoose.connect(mongoUri);
        
        console.log('Deleting existing modules...');
        await LearningModule.deleteMany({});
        
        console.log(`Inserting ${modules.length} high-quality modules with 5 questions each...`);
        await LearningModule.insertMany(modules);
        
        console.log('Seeding completed successfully!');
        process.exit(0);
    } catch (error) {
        console.error('Seeding failed:', error);
        process.exit(1);
    }
};

seedDB();
